apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

namespace: my-namespace

commonLabels:
  environment: test

images:
  - name: nginx
    newTag: 1.27
